seed: 6669
dataset: mimic3
task: m
use_cuda: true
code_size: 48
graph_size: 32
hidden_size: 256
t_attention_size: 32
batch_size: 32
epochs: 15
output_dir: "./runs/chet_text_embeddings_m" # output directory for saving checkpoints
pretrained_embeddings_path: pretraining/bge_embeddings.pt
freeze_embeddings: true